#!/bin/bash

go get github.com/go-sql-driver/mysql
go get github.com/eryx/imaging

go build -ldflags "-w -s" -o ./bin/lessids-cli ./src/cli.go 
go build -ldflags "-w -s" -o ./bin/lessids ./src/main.go 


