#!/bin/bash

echo "DIRs"
find ./src -type d  | wc -l
echo "FILEs"
find ./src -type f  | wc -l
echo "LINEs"
find ./src -name "*.go" |xargs cat|grep -v ^$|wc -l
echo "LINEs TPL"
find ./src -name "*.tpl" |xargs cat|grep -v ^$|wc -l
echo "DETAILs"
find ./src -type f -name "*.go" | xargs wc -l | sort -n

files=`find ./src -type f -name "*.go" |xargs`
for files in $file; do
    echo ${file}
    gofmt -tabwidth=4 -tabs=false -w=true ${file}
done

go build -ldflags "-w -s" -o ./bin/lessids-cli ./src/cli.go 
go build -ldflags "" -o ./bin/lessids-server ./src/main.go 

./bin/lessids-server

