#!/bin/bash

files=`find . -type f -name "*.go" |xargs`
for file in $files; do
    gofmt -s -w ${file}
done

rm -f ./bin/lessos-iam

go build -ldflags "-w -s" -o ./bin/lessos-iam ./cmd/main.go 

./bin/lessos-iam -logtostderr=true

