#!/bin/sh

set -eu

USER="lessiam"
GROUP="$USER"

chown -R $USER:$GROUP /opt/lessiam

chmod +x /opt/lessiam/bin/lessiam

chown root:root /etc/init.d/lessiam
chmod +x /etc/init.d/lessiam

# Automatically added by dh_installinit
if [ -x "/etc/init.d/lessiam" ]; then
	update-rc.d lessiam defaults >/dev/null
	invoke-rc.d lessiam start || exit $?
fi
# End automatically added section

