#!/bin/sh

set -e

if [ "$1" = "purge" ]
then
	rm -rf /opt/lessiam
	userdel lessiam
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d lessiam remove >/dev/null
fi
# End automatically added section

