#!/bin/sh

set -e

if [ "$1" = "purge" ]
then
	rm -rf /opt/lessids
	userdel lessids
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d lessids remove >/dev/null
fi
# End automatically added section

