// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package iamapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_TEXT MsgType = 0
	MsgType_HTML MsgType = 1
)

var MsgType_name = map[int32]string{
	0: "TEXT",
	1: "HTML",
}

var MsgType_value = map[string]int32{
	"TEXT": 0,
	"HTML": 1,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type MsgItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action               uint32   `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	ToUser               string   `protobuf:"bytes,3,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	ToEmail              string   `protobuf:"bytes,4,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	FromUser             string   `protobuf:"bytes,5,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty"`
	FromEmail            string   `protobuf:"bytes,6,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	Priority             uint32   `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Title                string   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Retry                uint32   `protobuf:"varint,10,opt,name=retry,proto3" json:"retry,omitempty"`
	Type                 MsgType  `protobuf:"varint,11,opt,name=type,proto3,enum=iamapi.MsgType" json:"type,omitempty"`
	Log                  string   `protobuf:"bytes,12,opt,name=log,proto3" json:"log,omitempty"`
	Posted               uint32   `protobuf:"varint,13,opt,name=posted,proto3" json:"posted,omitempty"`
	Created              uint32   `protobuf:"varint,14,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint32   `protobuf:"varint,15,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgItem) Reset()         { *m = MsgItem{} }
func (m *MsgItem) String() string { return proto.CompactTextString(m) }
func (*MsgItem) ProtoMessage()    {}
func (*MsgItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *MsgItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgItem.Unmarshal(m, b)
}
func (m *MsgItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgItem.Marshal(b, m, deterministic)
}
func (m *MsgItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgItem.Merge(m, src)
}
func (m *MsgItem) XXX_Size() int {
	return xxx_messageInfo_MsgItem.Size(m)
}
func (m *MsgItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgItem.DiscardUnknown(m)
}

var xxx_messageInfo_MsgItem proto.InternalMessageInfo

func (m *MsgItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgItem) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *MsgItem) GetToUser() string {
	if m != nil {
		return m.ToUser
	}
	return ""
}

func (m *MsgItem) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func (m *MsgItem) GetFromUser() string {
	if m != nil {
		return m.FromUser
	}
	return ""
}

func (m *MsgItem) GetFromEmail() string {
	if m != nil {
		return m.FromEmail
	}
	return ""
}

func (m *MsgItem) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *MsgItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgItem) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MsgItem) GetRetry() uint32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *MsgItem) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_TEXT
}

func (m *MsgItem) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *MsgItem) GetPosted() uint32 {
	if m != nil {
		return m.Posted
	}
	return 0
}

func (m *MsgItem) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *MsgItem) GetUpdated() uint32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterEnum("iamapi.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*MsgItem)(nil), "iamapi.MsgItem")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x9b, 0x26, 0xe9, 0xd4, 0x7e, 0x30, 0x88, 0xae, 0x4a, 0xa1, 0xe8, 0xa5, 0x78,
	0xe8, 0x41, 0x7f, 0x43, 0x41, 0xc1, 0x5e, 0x4a, 0x04, 0x6f, 0x25, 0x6d, 0xd6, 0xb2, 0x90, 0x38,
	0xcb, 0xee, 0xf4, 0x90, 0x9b, 0x3f, 0x5d, 0x76, 0xb6, 0x7a, 0x9b, 0x67, 0x9f, 0x79, 0x37, 0xe1,
	0x5d, 0x18, 0x71, 0x67, 0xb5, 0x5f, 0x59, 0x47, 0x4c, 0x98, 0x99, 0xaa, 0xad, 0xac, 0x79, 0xf8,
	0xe9, 0x43, 0xbe, 0xf1, 0xc7, 0x37, 0xd6, 0x2d, 0x4e, 0xa0, 0x67, 0x6a, 0x95, 0x2c, 0x92, 0xe5,
	0x70, 0xdb, 0x33, 0x35, 0x5e, 0x43, 0x56, 0x1d, 0xd8, 0xd0, 0xb7, 0xea, 0x2d, 0x92, 0xe5, 0x78,
	0x7b, 0x26, 0xbc, 0x81, 0x9c, 0x69, 0x77, 0xf2, 0xda, 0xa9, 0xbe, 0x2c, 0x67, 0x4c, 0x1f, 0x5e,
	0x3b, 0xbc, 0x85, 0x82, 0x69, 0xa7, 0xdb, 0xca, 0x34, 0x2a, 0x15, 0x93, 0x33, 0xad, 0x03, 0xe2,
	0x3d, 0x0c, 0xbf, 0x1c, 0xb5, 0x31, 0x35, 0x10, 0x57, 0x84, 0x03, 0xc9, 0xcd, 0x01, 0x44, 0xc6,
	0x64, 0x26, 0x56, 0xd6, 0x63, 0xf6, 0x0e, 0x0a, 0xeb, 0x0c, 0x39, 0xc3, 0x9d, 0xca, 0xe5, 0x4f,
	0xfe, 0x19, 0xaf, 0x60, 0xc0, 0x86, 0x1b, 0xad, 0x0a, 0x49, 0x45, 0x40, 0x84, 0x74, 0x4f, 0x75,
	0xa7, 0x86, 0x72, 0x28, 0x73, 0xd8, 0x74, 0x9a, 0x5d, 0xa7, 0x40, 0xae, 0x88, 0x80, 0x8f, 0x90,
	0x86, 0x5a, 0xd4, 0x68, 0x91, 0x2c, 0x27, 0xcf, 0xd3, 0x55, 0xac, 0x65, 0xb5, 0xf1, 0xc7, 0xb2,
	0xb3, 0x7a, 0x2b, 0x12, 0x67, 0xd0, 0x6f, 0xe8, 0xa8, 0x2e, 0xe5, 0xb6, 0x30, 0x86, 0x6a, 0x2c,
	0x79, 0xd6, 0xb5, 0x1a, 0xc7, 0x6a, 0x22, 0xa1, 0x82, 0xfc, 0xe0, 0x74, 0x15, 0xc4, 0x44, 0xc4,
	0x1f, 0x06, 0x73, 0xb2, 0xb5, 0x98, 0x69, 0x34, 0x67, 0x7c, 0x9a, 0xcb, 0x0b, 0x84, 0xcf, 0x61,
	0x01, 0x69, 0xb9, 0xfe, 0x2c, 0x67, 0x17, 0x61, 0x7a, 0x2d, 0x37, 0xef, 0xb3, 0x64, 0x9f, 0xc9,
	0x83, 0xbd, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xd9, 0xbf, 0x16, 0xbf, 0x01, 0x00, 0x00,
}
