// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package iamauth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthKey struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey" json:"access_key,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=secret_key,json=secretKey" json:"secret_key,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthKey) Reset()         { *m = AuthKey{} }
func (m *AuthKey) String() string { return proto.CompactTextString(m) }
func (*AuthKey) ProtoMessage()    {}
func (*AuthKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_9750619323b5ef70, []int{0}
}
func (m *AuthKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthKey.Unmarshal(m, b)
}
func (m *AuthKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthKey.Marshal(b, m, deterministic)
}
func (dst *AuthKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthKey.Merge(dst, src)
}
func (m *AuthKey) XXX_Size() int {
	return xxx_messageInfo_AuthKey.Size(m)
}
func (m *AuthKey) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthKey.DiscardUnknown(m)
}

var xxx_messageInfo_AuthKey proto.InternalMessageInfo

func (m *AuthKey) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *AuthKey) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *AuthKey) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type UserPayload struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Roles                []uint32 `protobuf:"varint,4,rep,packed,name=roles" json:"roles,omitempty"`
	Groups               []uint32 `protobuf:"varint,5,rep,packed,name=groups" json:"groups,omitempty"`
	Expired              int64    `protobuf:"varint,9,opt,name=expired" json:"expired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPayload) Reset()         { *m = UserPayload{} }
func (m *UserPayload) String() string { return proto.CompactTextString(m) }
func (*UserPayload) ProtoMessage()    {}
func (*UserPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_9750619323b5ef70, []int{1}
}
func (m *UserPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayload.Unmarshal(m, b)
}
func (m *UserPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayload.Marshal(b, m, deterministic)
}
func (dst *UserPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayload.Merge(dst, src)
}
func (m *UserPayload) XXX_Size() int {
	return xxx_messageInfo_UserPayload.Size(m)
}
func (m *UserPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayload proto.InternalMessageInfo

func (m *UserPayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserPayload) GetRoles() []uint32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *UserPayload) GetGroups() []uint32 {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *UserPayload) GetExpired() int64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

type AppPayload struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	AccessKey            string   `protobuf:"bytes,3,opt,name=access_key,json=accessKey" json:"access_key,omitempty"`
	Created              int64    `protobuf:"varint,9,opt,name=created" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppPayload) Reset()         { *m = AppPayload{} }
func (m *AppPayload) String() string { return proto.CompactTextString(m) }
func (*AppPayload) ProtoMessage()    {}
func (*AppPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_9750619323b5ef70, []int{2}
}
func (m *AppPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppPayload.Unmarshal(m, b)
}
func (m *AppPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppPayload.Marshal(b, m, deterministic)
}
func (dst *AppPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppPayload.Merge(dst, src)
}
func (m *AppPayload) XXX_Size() int {
	return xxx_messageInfo_AppPayload.Size(m)
}
func (m *AppPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AppPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AppPayload proto.InternalMessageInfo

func (m *AppPayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppPayload) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AppPayload) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *AppPayload) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthKey)(nil), "iamauth.AuthKey")
	proto.RegisterType((*UserPayload)(nil), "iamauth.UserPayload")
	proto.RegisterType((*AppPayload)(nil), "iamauth.AppPayload")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_9750619323b5ef70) }

var fileDescriptor_auth_9750619323b5ef70 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0x87, 0xd9, 0xcd, 0xdd, 0x85, 0x1d, 0xd1, 0x22, 0x88, 0xa4, 0x11, 0x96, 0xad, 0xb6, 0xb2,
	0xf1, 0x09, 0xae, 0xb6, 0x91, 0x05, 0x2b, 0x0b, 0x89, 0xc9, 0xe0, 0x05, 0xef, 0x4c, 0x98, 0x24,
	0x60, 0xde, 0x5e, 0x36, 0x89, 0x1c, 0x5c, 0x71, 0xdd, 0x7c, 0xbf, 0x8f, 0xcc, 0x9f, 0x00, 0xa8,
	0x14, 0x0f, 0x4f, 0x9e, 0x5c, 0x74, 0x82, 0x5b, 0x75, 0x5a, 0x71, 0x7a, 0x07, 0xbe, 0x4f, 0xf1,
	0xf0, 0x82, 0x59, 0x3c, 0x02, 0x28, 0xad, 0x31, 0x84, 0x8f, 0x6f, 0xcc, 0xb2, 0x1b, 0xbb, 0x79,
	0x58, 0x86, 0x9a, 0x34, 0x1d, 0x50, 0x13, 0xc6, 0xa2, 0xfb, 0xaa, 0x6b, 0xb2, 0x6a, 0x01, 0x9b,
	0x14, 0x90, 0x24, 0x2b, 0xa2, 0xd4, 0x53, 0x86, 0x9b, 0xb7, 0x80, 0xf4, 0xaa, 0xf2, 0xd1, 0x29,
	0x23, 0xee, 0xa0, 0xb7, 0xa6, 0x35, 0xee, 0xad, 0x59, 0x9f, 0xfc, 0xa8, 0x13, 0xb6, 0x5e, 0xa5,
	0x16, 0xf7, 0xb0, 0x25, 0x77, 0xc4, 0x20, 0x37, 0x23, 0x9b, 0x6f, 0x97, 0x0a, 0xe2, 0x01, 0x76,
	0x5f, 0xe4, 0x92, 0x0f, 0x72, 0x5b, 0xe2, 0x46, 0x42, 0x02, 0xc7, 0x5f, 0x6f, 0x09, 0x8d, 0x1c,
	0xc6, 0x6e, 0x66, 0xcb, 0x3f, 0x4e, 0x16, 0x60, 0xef, 0xfd, 0x95, 0xc9, 0x65, 0xd9, 0xfe, 0xbc,
	0xec, 0xc5, 0xf9, 0xec, 0xf2, 0x7c, 0x09, 0x5c, 0x13, 0xaa, 0x78, 0x1e, 0xd5, 0xf0, 0x73, 0x57,
	0xbe, 0xf4, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x62, 0x93, 0x59, 0x60, 0x01, 0x00, 0x00,
}
