#!/usr/bin/php

<?php

$opt = getopt("r:");
$rel = isset($opt['r']) ? intval($opt['r']) : '1';

$arch = trim(shell_exec("arch"));

if ($arch != "x86_64") {
    die("The architecture of the operating system does not support: $arch");
}

$basedir = realpath(__DIR__.'/../..');

$ver = file_get_contents($basedir."/src/conf/conf.go");
if (!preg_match("/Version\ +\=\ +\"(.*)\"/", $ver, $mat)) {
    die("Can not get version");
}
$ver = $mat[1];

$pkgname = "lessids";

$cmd = "
rm -rf /tmp/rpm-tmp*
rm -rf /tmp/{BUILD,RPMS,SOURCES,SPECS,SRPMS,BUILDROOT}
mkdir -p /tmp/{BUILD,RPMS,SOURCES,SPECS,SRPMS,BUILDROOT}

rm -rf /tmp/SOURCES/{$pkgname}*

mkdir -p /tmp/SOURCES/{$pkgname}-{$ver}/etc
mkdir -p /tmp/SOURCES/{$pkgname}-{$ver}/bin
mkdir -p /tmp/SOURCES/{$pkgname}-{$ver}/var
mkdir -p /tmp/SOURCES/{$pkgname}-{$ver}/static
mkdir -p /tmp/SOURCES/{$pkgname}-{$ver}/misc/rhel

rm -f $basedir/bin/lessids*

cp -rp $basedir/static/jquery /tmp/SOURCES/{$pkgname}-{$ver}/static/
cp -rp $basedir/static/ids /tmp/SOURCES/{$pkgname}-{$ver}/static/
cp -rp $basedir/static/twitter-bootstrap /tmp/SOURCES/{$pkgname}-{$ver}/static/

mkdir -p /tmp/SOURCES/{$pkgname}-{$ver}/static/lessui/master
cp -rp $basedir/static/lessui/master/img /tmp/SOURCES/{$pkgname}-{$ver}/static/lessui/master/
cp -rp $basedir/static/lessui/master/css /tmp/SOURCES/{$pkgname}-{$ver}/static/lessui/master/
cp -rp $basedir/static/lessui/master/js /tmp/SOURCES/{$pkgname}-{$ver}/static/lessui/master/

cp -rp $basedir/src /tmp/SOURCES/{$pkgname}-{$ver}/
cp -rp $basedir/deps /tmp/SOURCES/{$pkgname}-{$ver}/

cp -rp $basedir/build /tmp/SOURCES/{$pkgname}-{$ver}/
cp -rp $basedir/LICENSE /tmp/SOURCES/{$pkgname}-{$ver}/
cp -rp $basedir/README.md /tmp/SOURCES/{$pkgname}-{$ver}/

cp -rp $basedir/etc/lessids.conf.dist /tmp/SOURCES/{$pkgname}-{$ver}/etc/lessids.conf
cp -rp $basedir/misc/rhel/init.d-scripts /tmp/SOURCES/{$pkgname}-{$ver}/misc/rhel/init.d-scripts

cd /tmp/SOURCES
tar zcf {$pkgname}-{$ver}.tar.gz {$pkgname}-{$ver}
";

shell_exec($cmd);

$os = "el6";

$file = "{$basedir}/misc/rhel/rpm.spec";
$spec = file_get_contents($file);

$mat = array(
    "/Name:\ +(.*?)\n/",
    "/Version:\ +(.*?)\n/",
    "/Release:\ +(.*?)\n/",
    "/Source0:\ +(.*?)\n/",
);
$rep = array(
    "Name: lessids\n",
    "Version: {$ver}\n",
    "Release: {$rel}\n",
    "Source0: lessids-{$ver}.tar.gz\n",
);
$spec = preg_replace($mat, $rep, $spec);
$spec = str_replace('%{?dist}', '', $spec);
$spec = preg_replace("/Release:\ +(.*?)\n/", "Release: $1%{?dist}\n", $spec);

$specfile = "/tmp/lessids-{$ver}-rpm.spec";
file_put_contents($specfile, $spec);

$cmd = "rpmbuild -ba $specfile";
$cmd.= " --define='_tmppath /tmp'";
$cmd.= " --define='_builddir /tmp/BUILD'";
$cmd.= " --define='_topdir /tmp/'";
$cmd.= " --define='dist .{$os}'";

$retarr = array();
$retint = 0;
$retstr = exec($cmd, $retarr, $retint);
if ($retint > 0) {
    $_errstr = $cmd;
    foreach ($retarr as $v) {
        $_errstr .= "\n".$v;     
    }
}
shell_exec($cmd);

$cmd = "cp /tmp/RPMS/$arch/lessids-{$ver}*.rpm ~/";
shell_exec($cmd);

die();
